name: LLVM Compilation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download LLVM Source Code
        run: |
          wget -O llvm.tar.gz https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-16.0.0.tar.gz
          tar xzf llvm.tar.gz
          mv llvm-project-llvmorg-16.0.0 llvm-project
          
      - name: Build LLVM
        run: |
          cd llvm-project
          mkdir build
          cd build
          cp ../../CMakeLists.txt .
          cmake -GNinja -DLLVM_ENABLE_PROJECTS="llvm;clang" -DCMAKE_BUILD_TYPE=Release ..
          ninja

      - name: Create LLVM Archive
        run: |
          cd llvm-project/build
          ninja package

      - name: Upload LLVM Archive
        uses: actions/upload-artifact@v2
        with:
          name: llvm-artifacts
          path: llvm-project/build/llvm-*.tar.gz
