name: LLVM Compliation

on:
  push:
    branches:
      - main
  
jobs:
  build-1:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable

      - name: Cache LLVM and Clang
        uses: actions/cache@v3
        with:
          path: |
            C:/Program Files/LLVM
            ./llvm
          key: llvm-16.0.0

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1.8.3
        with:
          version: "16.0.0"
          directory: ${{ runner.temp }}/llvm
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}

      - name: Install libtinfo5
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y libtinfo5

      - name: Cache crates
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Test
        run: ls ${{ env.LLVM_PATH }}

      - run: cargo fmt --check
      - run: cargo build --verbose
        env:
          LLVM_SYS_160_PREFIX: ${{ env.LLVM_PATH }}
      - run: cargo test --verbose
        env:
          LLVM_SYS_160_PREFIX: ${{ env.LLVM_PATH }}
