name: LLVM Compliation

on:
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Cache LLVM and Clang
        uses: actions/cache@v3
        with:
          path: |
            C:/Program Files/LLVM
            ./llvm
          key: llvm-16.0.0

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1.8.3
        with:
          version: "16.0.0"
          directory: ${{ runner.temp }}/llvm

      - name: Linking libLLVM.so
        if: contains(matrix.os, 'ubuntu')
        run: find /usr/local/lib -name "libLLVM*.so*"

