name: Rust tests

on:
  push:
    paths:
      - '**.rs'
      - '**.toml'
      - '**.yml'
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    name: "On ${{ matrix.os }}, with ${{ matrix.llvm-version[1] }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - windows-latest
          - macos-latest
        llvm-version:
          - ["14.0", "llvm-14.0", "14-0"]
          
    steps:
    - uses: actions/checkout@v3

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.3.0
    
    - name: Cache LLVM and Clang
      id: cache-llvm
      uses: actions/cache@v3
      with:
        path: ${{ runner.temp }}/llvm
        key: ${{ matrix.llvm-version[1] }}-${{ matrix.os }}

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: ${{ matrix.llvm-version[0] }}
        directory: ${{ runner.temp }}/llvm
        cached: ${{ steps.cache-llvm.outputs.cache-hit }}

    - name: Build
      run: cargo build --release --features llvm${{ matrix.llvm-version[2] }} --verbose

    - name: Run tests
      run: cargo test --release --features llvm${{ matrix.llvm-version[2] }} --verbose
