name: LLVM Compilation

on:
    push:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download LLVM Source Code
        run: |
          wget -O llvm.tar.gz https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-16.0.6.tar.gz
          tar xzf llvm.tar.gz

      - name: Build LLVM
        run: |
          ls
