name: Windows CI

on: [push]

jobs:
  x86_64-windows-llvm:
    runs-on: windows-2022
    steps:
      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@cec98b9d092141f74527d0afa6feb2af698cfe89 # v1.12.1

      - name: Cache LLVM
        id: cache-llvm
        uses: actions/cache@v3
        with:
          path: D:\a\llvm
          key: llvm-libs-16.0.3-msvc

      - name: Compile LLVM
        if: steps.cache-llvm.outputs.cache-hit == 'true'
        run: |
          docker build -t windows-x86_64-release ./containers/windows-2022
          docker run ./containers/windows-2022

